version: '3.5'

services:
  app:
    build:
      context: ./app
    ports:
      - "9000:9000"

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx:delegated
      - ./nginx/ssl:/etc/nginx/ssl
